#!/bin/bash

START="no"

if [ "$XIM" = "fcitx5" -o "$XIM" = "fcitx" ]; then
  START="yes"
fi

if [ "$XIM_PROGRAM" = "fcitx5" -o "$XIM_PROGRAM" = "fcitx" ]; then
  START="yes"
fi

if [ "$GTK_IM_MODULE" = "fcitx5" -o "$GTK_IM_MODULE" = "fcitx" ]; then
  START="yes"
fi

if [ "$QT_IM_MODULE" = "fcitx5" -o "$QT_IM_MODULE" = "fcitx" ]; then
  START="yes"
fi

if [ "$START" = "no" ]; then
  exit 0
fi

# sleep for a little while to avoid duplicate startup
sleep 2

# Test whether fcitx5 is running correctly with dbus...
fcitx5-remote > /dev/null 2>&1

if [ $? = "1" ]; then
    echo "Fcitx5 seems is not running"
    fcitx5
else
    echo "Fcitx5 is running correctly."
fi
