#!/bin/sh 

while [ 1 ] ; do

if [ "`ls -l /sbin/netconfig | sed 's/.*-> *//'`" = "netconfig.tradnet" ]; then
  NETCONFIG_ITEM="planet"
  NETCONFIG_MSG="ネットワーク設定ツールをplanetに変更(要リブート)"
else
  NETCONFIG_ITEM="tradnet"
  NETCONFIG_MSG="ネットワーク設定ツールをtradnetに変更(要リブート)"
fi

TMP_REPLY=`mktemp /tmp/tmp_reply_$$.XXXXXX`

dialog --title "Plamo Linux セットアップメニュー" --menu \
"Plamo では以下の簡易設定ツールを用意しています．どれを実行しますか？\
" \
22 77 15 \
"adduser" "一般ユーザ追加(Xの利用は必ずadduserで追加したユーザで!)" \
"xfplamoconfig" "X.orgサーバの設定(推奨)" \
"pkgtool" "パッケージ管理" \
"mkinfodir"  "/usr/share/info/dir を再構築" \
"netconfig" "ネットワークの設定" \
"$NETCONFIG_ITEM" "$NETCONFIG_MSG" \
"pppsetup" "PPPのセットアップ" \
"grubconfig" "ブートローダ grub の設定" \
"liloconfig" "ブートローダ lilo の設定" \
"osldrconfig" "Windows NT/2000/XP の OS ローダ + lilo の設定" \
"timeconfig" "時間帯の設定" \
"Exit" "setup終了" 2> $TMP_REPLY
  if [ $? = 1 -o $? = 255 ]; then
    rm -f $TMP_REPLY
    exit
  fi
TG="`cat $TMP_REPLY`"
rm -f $TMP_REPLY
clear
if [ "$TG" = "Exit" ] ; then
  exit
elif [ "$TG" = "xfplamoconfig" ] ; then
  PATH="$PATH:/usr/X11/bin"
  xfplamoconfig
  echo "  X の設定が成功したら adduser でユーザを作成し、"
  echo "  一般ユーザで X 環境を利用してください。"
elif [ "$TG" = "xf86cfg" ] ; then
  PATH="$PATH:/usr/X11/bin"
  xf86cfg -textmode
  echo "  X の設定が成功したら adduser でユーザを作成し、"
  echo "  一般ユーザで X 環境を利用してください。"
elif [ "$TG" = "xf86config" ] ; then
  PATH="$PATH:/usr/X11/bin"
  xf86config
  echo "  X の設定が成功したら adduser でユーザを作成し、"
  echo "  一般ユーザで X 環境を利用してください。"
else
  $TG
fi

echo "【setupに戻ります。何かキーを押してください。】"
read TG

done
