# Invite the new admin to register their machine with the Linux Counter:
if [ ! -f var/spool/mail/root ]; then
  mv tmp/root.new var/spool/mail/root
else
  cat tmp/root.new >> var/spool/mail/root
  rm tmp/root.new
fi
# Do that symlink thing:
( cd usr/share/man ; rm -rf cat1 )
( cd usr/share/man ; ln -sf /var/cache/man/cat1 cat1 )
( cd usr/share/man ; rm -rf cat2 )
( cd usr/share/man ; ln -sf /var/cache/man/cat2 cat2 )
( cd usr/share/man ; rm -rf cat3 )
( cd usr/share/man ; ln -sf /var/cache/man/cat3 cat3 )
( cd usr/share/man ; rm -rf cat4 )
( cd usr/share/man ; ln -sf /var/cache/man/cat4 cat4 )
( cd usr/share/man ; rm -rf cat5 )
( cd usr/share/man ; ln -sf /var/cache/man/cat5 cat5 )
( cd usr/share/man ; rm -rf cat6 )
( cd usr/share/man ; ln -sf /var/cache/man/cat6 cat6 )
( cd usr/share/man ; rm -rf cat7 )
( cd usr/share/man ; ln -sf /var/cache/man/cat7 cat7 )
( cd usr/share/man ; rm -rf cat8 )
( cd usr/share/man ; ln -sf /var/cache/man/cat8 cat8 )
( cd usr/share/man ; rm -rf cat9 )
( cd usr/share/man ; ln -sf /var/cache/man/cat9 cat9 )
( cd usr/share/man ; rm -rf catn )
( cd usr/share/man ; ln -sf /var/cache/man/catn catn )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat1 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat1 cat1 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat2 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat2 cat2 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat3 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat3 cat3 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat4 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat4 cat4 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat5 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat5 cat5 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat6 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat6 cat6 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat7 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat7 cat7 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat8 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat8 cat8 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf cat9 )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat9 cat9 )
( cd usr/share/man/ja_JP.eucJP ; rm -rf catn )
( cd usr/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/catn catn )
( cd usr/local/share/man ; rm -rf cat1 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat1 cat1 )
( cd usr/local/share/man ; rm -rf cat2 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat2 cat2 )
( cd usr/local/share/man ; rm -rf cat3 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat3 cat3 )
( cd usr/local/share/man ; rm -rf cat4 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat4 cat4 )
( cd usr/local/share/man ; rm -rf cat5 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat5 cat5 )
( cd usr/local/share/man ; rm -rf cat6 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat6 cat6 )
( cd usr/local/share/man ; rm -rf cat7 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat7 cat7 )
( cd usr/local/share/man ; rm -rf cat8 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat8 cat8 )
( cd usr/local/share/man ; rm -rf cat9 )
( cd usr/local/share/man ; ln -sf /var/cache/man/cat9 cat9 )
( cd usr/local/share/man ; rm -rf catn )
( cd usr/local/share/man ; ln -sf /var/cache/man/catn catn )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat1 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat1 cat1 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat2 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat2 cat2 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat3 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat3 cat3 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat4 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat4 cat4 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat5 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat5 cat5 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat6 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat6 cat6 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat7 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat7 cat7 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat8 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat8 cat8 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf cat9 )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/cat9 cat9 )
( cd usr/local/share/man/ja_JP.eucJP ; rm -rf catn )
( cd usr/local/share/man/ja_JP.eucJP ; ln -sf /var/cache/man/ja_JP.eucJP/catn catn )
# Other symlinks:
( cd usr ; rm -rf adm )
( cd usr ; ln -sf /var/adm adm )
( cd usr ; rm -rf preserve )
( cd usr ; ln -sf /var/preserve preserve )
( cd usr ; rm -rf spool )
( cd usr ; ln -sf /var/spool spool )
( cd usr ; rm -rf tmp )
( cd usr ; ln -sf /var/tmp tmp )
( cd usr ; rm -rf man )
( cd usr ; ln -sf share/man man )
( cd usr ; rm -rf doc )
( cd usr ; ln -sf share/doc doc )
( cd usr ; rm -rf info )
( cd usr ; ln -sf share/info info )
( cd var ; rm -rf rwho )
( cd var ; ln -sf /var/spool/rwho rwho )
( cd var ; rm -rf locks )
( cd var ; ln -sf lock locks )
( cd var ; rm -rf adm )
( cd var ; ln -sf log adm )
( cd var ; rm -rf mail )
( cd var ; ln -sf /var/spool/mail mail )
( cd var/spool ; rm -rf locks )
( cd var/spool ; ln -sf /var/lock locks )
( cd var/log ; rm -rf utmp )
( cd var/log ; ln -sf /var/run/utmp utmp )
# These are for Japanese locale
( cd usr/share/locale ; rm -rf ja )
( cd usr/share/locale ; ln -sf ja_JP.eucJP ja )
( cd usr/share/locale ; rm -rf ja_JP )
( cd usr/share/locale ; ln -sf ja_JP.eucJP ja_JP )
