#!/bin/sh

# $MTPT に chroot してから実行される部分

expand_mes () {
    source /sbin/grubconfig.mes
}

PROBE=/sbin/fdisk
crunch () { # remove extra whitespace
    read STRING;
    echo $STRING
}

ROOT_DEVICE=`cat /tmp/grub_ROOT_DEVICE`

expand_mes
/bin/dialog --title "grub install (1)" --infobox "$install_mes_1" 6 70

grub-install --target=i386-pc --no-floppy --grub-setup=/bin/true $ROOT_DEVICE
sleep 3
LANG=C
grub-mkconfig -o /boot/grub/grub.cfg
sleep 3
LANG=ja_JP.UTF-8
if [ ! -f /boot/grub/grub.cfg ]; then
    /bin/dialog --title "grub.cfg build error" --msgbox	"$cfg_err_mes" 6 70
    exit 1
fi
    
cat <<'EOF' > /tmp/grub.cfg.tmp
This is the generated grub.cfg.
-----------------------------------------------------------------
EOF
cat $MTPT/boot/grub/grub.cfg >> /tmp/grub.cfg.tmp
cat <<'EOF' >> /tmp/grub.cfg.tmp
-----------------------------------------------------------------
EOF

/bin/dialog --title "contents of grub.cfg" --textbox /tmp/grub.cfg.tmp  40 76

/bin/dialog --title "continue?" --yesno "$continue_mes"  6 60
if [ $? != 0 ]; then
    rm -f /tmp/grub.cfg.tmp
    /bin/dialog --title "User exit" --msgbox "$exit_mes" 6 70
    exit 1
fi

cat <<EOF > /tmp/tmpscript
#!/bin/sh
/bin/dialog --title "select HDD for grub" --menu \
"$tgt_mes" 20 74 4 \\
EOF

# これをしないとfdiskの出力が日本語になる
export LANG=C
$PROBE -l | grep -v ram | grep "^Disk " | grep -v "identifier" > /tmp/SeTdlist
export LANG=ja_JP.UTF-8
cat /tmp/SeTdlist | while [ 0 ]; do
    read DISK;
    if [ "$DISK" = "" ]; then
	break;
    fi
    NAME=`echo $DISK | crunch | cut -f2 -d' ' | sed "s/://"`
    SIZE=`echo $DISK | crunch | cut -f3 -d' ' `
    UNIT=`echo $DISK | crunch | cut -f4 -d' ' | sed "s/,//"`
    echo "\"$NAME\" \"$SIZE $UNIT\" \\" >> /tmp/tmpscript
done
echo "2> /tmp/return" >> /tmp/tmpscript

. /tmp/tmpscript
if [ $? = 1 -o $? = 255 ]; then
    rm /tmp/tmpscript
    exit 255 # user abort
fi
grub_HDD=`cat /tmp/return`

expand_mes
dialog --title "install grub into MBR" --yesno \
"$mbr_mes" 10 70
if [ $? = 0 ]; then
    dialog --title "installing grub" --infobox \
	"$install_mes1" 10 70
    grub-install --target=i386-pc $grub_HDD
    sleep 3
    if [ $? = 0 ]; then
	dialog --title "install succeeded" --msgbox \
	    "$install_mes2" 10 70
    else
	dialog --title "install failed" --msgbox \
	    "$install_mes3" 10 70
	exit 1
    fi
else
    dialog --title "Quit grub install" --infobox \
	"$quit_mes" 10 70
    exit 1
fi

if [ -x /sbin/grub_partuuid.sh ]; then
    dialog --title "convert root device name?" --yesno \
	   "$uuid_mes1" 10 70
    if [ $? -eq 0 ]; then
	/sbin/grub_partuuid.sh
	if [ $? -eq 0 ]; then
	    dialog --title "grub.conf converted" --msgbox \
		   "$uuid_mes2" 10 70
	fi
    fi
fi
